# Generated by Django 4.0.6 on 2022-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_porfile_about_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=100)),
                ('t1', models.CharField(max_length=50)),
                ('t2', models.CharField(max_length=50)),
                ('t3', models.CharField(max_length=50)),
                ('t4', models.CharField(max_length=50)),
            ],
        ),
    ]
