# Generated by Django 4.0.6 on 2022-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descripsition', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='descriptions',
            new_name='descripsition',
        ),
    ]
