# Generated by Django 4.0.6 on 2022-08-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_services_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='descripsition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
