# Generated by Django 4.0.6 on 2022-08-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_services_descripsition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='descripsition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services_list',
            old_name='descripsition',
            new_name='description',
        ),
    ]
