# Generated by Django 4.0.6 on 2022-08-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_descripsition_services_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='p',
            new_name='percentage',
        ),
    ]
