# Generated by Django 4.0.6 on 2022-08-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='ln',
            new_name='linkedin',
        ),
    ]
