# Generated by Django 4.0.6 on 2022-08-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_fb_contact_us_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('total_client', models.CharField(max_length=50)),
                ('award_won', models.CharField(max_length=50)),
            ],
        ),
    ]
