# Generated by Django 4.0.6 on 2022-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_portfolio_item_project_client_portfolio_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='slider_one',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio_item',
            name='slider_three',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio_item',
            name='slider_two',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
