# Generated by Django 4.0.6 on 2022-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_portfolio_item_slider_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
