# Generated by Django 4.0.6 on 2022-08-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
