# Generated by Django 4.0.6 on 2022-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_pic_testimonial_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
