# Generated by Django 4.0.6 on 2022-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_portfolio_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog_item',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio_item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services_list',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
