# Generated by Django 4.0.6 on 2022-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_blog_description_alter_blog_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_item',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
