# Generated by Django 4.0.6 on 2022-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_blog_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='description',
            field=models.TextField(),
        ),
    ]
