# Generated by Django 4.0.6 on 2022-08-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_commnets'),
    ]

    operations = [
        migrations.AddField(
            model_name='commnets',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
