# Generated by Django 4.0.6 on 2022-08-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_contact_us_about_facebook_about_instagram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commnets',
        ),
    ]
