# Generated by Django 4.0.6 on 2022-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_delete_commnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='t1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='t2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='t3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='t4',
            field=models.CharField(max_length=100),
        ),
    ]
