# Generated by Django 4.0.6 on 2022-08-10 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_blog_item_slug_alter_portfolio_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='cv',
            field=models.FileField(default=datetime.datetime(2022, 8, 10, 11, 21, 10, 638635, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
