# Generated by Django 4.0.6 on 2022-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_hero_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
