# Generated by Django 4.0.6 on 2022-08-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_blog_item_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='img',
            new_name='Cover',
        ),
    ]
